// <auto-generated />
using A.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace A.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221028083252_Initialize_4")]
    partial class Initialize4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-rc.2.22472.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("A.Data.Entities.Division", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UpperName")
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpperName");

                    b.ToTable("divisions", (string)null);
                });

            modelBuilder.Entity("A.Data.Entities.Division", b =>
                {
                    b.HasOne("A.Data.Entities.Division", "UpperDivision")
                        .WithMany("DownDivisions")
                        .HasForeignKey("UpperName")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UpperDivision");
                });

            modelBuilder.Entity("A.Data.Entities.Division", b =>
                {
                    b.Navigation("DownDivisions");
                });
#pragma warning restore 612, 618
        }
    }
}
